### ISSUE TITLE
ACTIVIDAD INDIVIVUAL

### ISSUE THREAD

**Issue by Evelyn-sj13** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Evelyn-sj13-1#4]
[Sistemas numericos-matematicas discretas.pdf](https://github.com/user-attachments/files/16860139/Sistemas.numericos-matematicas.discretas.pdf)

**Comment by Berenice1719** [comment]
Portada 22/25
Procedimiento:20/25
Figuras, ilustraciones y fotografías 25/25
Resultados y conclusiones 17/25
Calificación Final 84/100

**Comment by josealfredo79** [comment]
Calificacion 17
